name: app_client
description: A new Flutter project.

publish_to: 'none' 

version: 0.3.1+1

environment:
  sdk: ">=2.17.5 <3.7.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.3
  path_provider: ^2.0.11
  drift: ^2.1.0
  sqlite3_flutter_libs: ^0.5.0
  path: ^1.8.2
  bloc: ^8.0.0
  peerdart: ^0.5.4
  battery: ^2.0.3

dependency_overrides:
  uuid: ^4.1.0
  super_native_extensions: '0.8.5'

  awesome_notifications_core: ^0.9.0 # <~ always ensure to use the latest version
  awesome_notifications: any # <~ this version is managed by awesome_notifications_core package

  cupertino_icons: ^1.0.2
  flutter_quill: ^9.2.10
  shared_preferences: ^2.2.2
  sqflite: ^2.3.2
  flutter_local_notifications: ^16.3.2
  workmanager: ^0.5.2

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  drift_dev: ^2.1.0
  build_runner: ^2.2.0

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/images/icon.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/no_notes.png
    - assets/images/No Notes - 1.png

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/NotoSansMono-Regular.ttf
        - asset: assets/fonts/NotoSansMono-Bold.ttf
        - asset: assets/fonts/NotoSansMono-Bold.ttf
        - asset: assets/fonts/NotoSansMono-Light.ttf

    - family: Nothing
      fonts:
        - asset: assets/fonts/nothing-font-5x7.ttf
    - family: Nothing -5x7
      fonts:
        - asset: assets/fonts/nothing-font-5x7.ttf
    - family: NothingIcon
      fonts:
        - asset: assets/fonts/icomoon.ttf
