name: app_client
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.3
  path_provider: ^2.0.11
  drift: ^2.1.0
  sqlite3_flutter_libs: ^0.5.0
  path: ^1.8.2
  bloc: ^8.0.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_launcher_icons: "^0.9.2"
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  drift_dev: ^2.1.0
  build_runner: ^2.2.0

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/images/icon.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/no_data.png
    - assets/images/no_notes.png
  
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/NotoSansMono-Regular.ttf
        - asset: assets/fonts/NotoSansMono-Bold.ttf
        - asset: assets/fonts/NotoSansMono-Bold.ttf
        - asset: assets/fonts/NotoSansMono-Light.ttf

    - family: Nothing
      fonts:
        - asset: assets/fonts/nothing-font-5x7.ttf
    - family: Nothing -5x7
      fonts:
        - asset: assets/fonts/nothing-font-5x7.ttf
    - family: NothingIcon
      fonts:
        - asset: assets/fonts/icomoon.ttf
